#  $$$$$$\  $$\                 $$\                     $$\   $$\
# $$  __$$\ $$ |                $$ |                    \__|  $$ |
# $$ /  \__|$$ |  $$\  $$$$$$\  $$ | $$$$$$\   $$$$$$$\ $$\ $$$$$$\   $$\   $$\
# \$$$$$$\  $$ | $$  |$$  __$$\ $$ |$$  __$$\ $$  _____|$$ |\_$$  _|  $$ |  $$ |
#  \____$$\ $$$$$$  / $$$$$$$$ |$$ |$$ /  $$ |$$ /      $$ |  $$ |    $$ |  $$ |
# $$\   $$ |$$  _$$<  $$   ____|$$ |$$ |  $$ |$$ |      $$ |  $$ |$$\ $$ |  $$ |
# \$$$$$$  |$$ | \$$\ \$$$$$$$\ $$ |\$$$$$$  |\$$$$$$$\ $$ |  \$$$$  |\$$$$$$$ |
#  \______/ \__|  \__| \_______|\__| \______/  \_______|\__|   \____/  \____$$ |
#                                                                     $$\   $$ |
#                                                                     \$$$$$$  |
#                                                                      \______/

# ---------------------------------------------------------------------------------
# -                             SKELOCITY CONFIG FILE                             -
# -      After editing any values in this config, please restart your server      -
# -                    Do NOT reload the plugin, it will break                    -
# ---------------------------------------------------------------------------------

# There are no current configurable options for the Skelocity Skript addon!